authorName: zhangli
experimentName: transformers-on-pubmed-sp-task
# 指定同时运行的 Trial 任务的最大数量。
trialConcurrency: 1
# maxExecDuration 指定实验的最大执行时间。 时间的单位为 {s, m, h, d}，其分别表示 {秒, 分钟, 小时, 天}。注意：maxExecDuration 设置的是 Experiment 执行的时间，不是 Trial 的。 如果 Experiment 达到了设置的最大时间，Experiment 不会停止，但不会再启动新的 Trial 作业。
maxExecDuration: 36h
# 指定 NNI 创建的最大 Trial 任务数，包括成功和失败的任务。
maxTrialNum: 200
#指定运行 Experiment 的平台，包括 local, remote, pai, kubeflow, frameworkcontroller. choice: local, remote, pai
trainingServicePlatform: local
localConfig:
  # 默认情况下，将使用所有可用的 GPU。
  gpuIndices: "0"
  # 用于指定 GPU 设备上的最大并发 Trial 的数量。
  maxTrialNumPerGpu: 1
  useActiveGpu: true

#logDir: /home/zhangli/nni/experiments
# 仅在 useAnnotation=True 时，才不需要填写 searchSpacePath。
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE # https://github.com/microsoft/nni/blob/master/docs/zh_CN/Tuner/BuiltinTuner.md
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python3 main.py
  # 必需字符串。 指定 Trial 文件的目录。 此目录将在 remote 模式下自动上传。
  codeDir: ../
  gpuNum: 1
